stages:
  - build
  - test

image: maven:3.8.1-jdk-11

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end -X" # Adding -X for verbose output

build:
  stage: build
  script:
    - echo "Building the project..."
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - echo "Running tests with verbose logging..."
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
