# .gitlab-ci.yml
stages:
  - build
  - test

# Specify the base image with Maven and JDK installed
image: maven:3.8.1-jdk-11

# Cache Maven dependencies to speed up the builds
cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end" # optional

# Build stage
build:
  stage: build
  script:
    - echo "Building the project..."
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/*.jar

# Test stage
test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
